project_path: .
ddconfig_path: PLEASE FILL
model_path: PLEASE FILL
data_path: PLEASE FILL

selected_columns: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136"]
target_columns: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136"]
target_column_types: # 'criterion' in training_spec must also be adapted
    "0": real
    "1": real
    "2": real
    "3": real
    "4": real
    "5": real
    "6": real
    "7": real
    "8": real
    "9": real
    "10": real
    "11": real
    "12": real
    "13": real
    "14": real
    "15": real
    "16": real
    "17": real
    "18": real
    "19": real
    "20": real
    "21": real
    "22": real
    "23": real
    "24": real
    "25": real
    "26": real
    "27": real
    "28": real
    "29": real
    "30": real
    "31": real
    "32": real
    "33": real
    "34": real
    "35": real
    "36": real
    "37": real
    "38": real
    "39": real
    "40": real
    "41": real
    "42": real
    "43": real
    "44": real
    "45": real
    "46": real
    "47": real
    "48": real
    "49": real
    "50": real
    "51": real
    "52": real
    "53": real
    "54": real
    "55": real
    "56": real
    "57": real
    "58": real
    "59": real
    "60": real
    "61": real
    "62": real
    "63": real
    "64": real
    "65": real
    "66": real
    "67": real
    "68": real
    "69": real
    "70": real
    "71": real
    "72": real
    "73": real
    "74": real
    "75": real
    "76": real
    "77": real
    "78": real
    "79": real
    "80": real
    "81": real
    "82": real
    "83": real
    "84": real
    "85": real
    "86": real
    "87": real
    "88": real
    "89": real
    "90": real
    "91": real
    "92": real
    "93": real
    "94": real
    "95": real
    "96": real
    "97": real
    "98": real
    "99": real
    "100": real
    "101": real
    "102": real
    "103": real
    "104": real
    "105": real
    "106": real
    "107": real
    "108": real
    "109": real
    "110": real
    "111": real
    "112": real
    "113": real
    "114": real
    "115": real
    "116": real
    "117": real
    "118": real
    "119": real
    "120": real
    "121": real
    "122": real
    "123": real
    "124": real
    "125": real
    "126": real
    "127": real
    "128": real
    "129": real
    "130": real
    "131": real
    "132": real
    "133": real
    "134": real
    "135": real
    "136": real


output_probabilities: false
map_to_id: false
device: cpu
seq_length: 48
inference_batch_size: 10

autoregression: true