project_path: .
model_name: default
read_format: parquet
ddconfig_path: PLEASE FILL

selected_columns: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136"]
target_columns: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136"]
target_column_types: # 'criterion' in training_spec must also be adapted
    "0": real
    "1": real
    "2": real
    "3": real
    "4": real
    "5": real
    "6": real
    "7": real
    "8": real
    "9": real
    "10": real
    "11": real
    "12": real
    "13": real
    "14": real
    "15": real
    "16": real
    "17": real
    "18": real
    "19": real
    "20": real
    "21": real
    "22": real
    "23": real
    "24": real
    "25": real
    "26": real
    "27": real
    "28": real
    "29": real
    "30": real
    "31": real
    "32": real
    "33": real
    "34": real
    "35": real
    "36": real
    "37": real
    "38": real
    "39": real
    "40": real
    "41": real
    "42": real
    "43": real
    "44": real
    "45": real
    "46": real
    "47": real
    "48": real
    "49": real
    "50": real
    "51": real
    "52": real
    "53": real
    "54": real
    "55": real
    "56": real
    "57": real
    "58": real
    "59": real
    "60": real
    "61": real
    "62": real
    "63": real
    "64": real
    "65": real
    "66": real
    "67": real
    "68": real
    "69": real
    "70": real
    "71": real
    "72": real
    "73": real
    "74": real
    "75": real
    "76": real
    "77": real
    "78": real
    "79": real
    "80": real
    "81": real
    "82": real
    "83": real
    "84": real
    "85": real
    "86": real
    "87": real
    "88": real
    "89": real
    "90": real
    "91": real
    "92": real
    "93": real
    "94": real
    "95": real
    "96": real
    "97": real
    "98": real
    "99": real
    "100": real
    "101": real
    "102": real
    "103": real
    "104": real
    "105": real
    "106": real
    "107": real
    "108": real
    "109": real
    "110": real
    "111": real
    "112": real
    "113": real
    "114": real
    "115": real
    "116": real
    "117": real
    "118": real
    "119": real
    "120": real
    "121": real
    "122": real
    "123": real
    "124": real
    "125": real
    "126": real
    "127": real
    "128": real
    "129": real
    "130": real
    "131": real
    "132": real
    "133": real
    "134": real
    "135": real
    "136": real


seq_length: 48
inference_batch_size: 10

export_onnx: true

model_spec:
  d_model: 64
  nhead: 4
  d_hid: 64
  nlayers: 4
training_spec:
  device: cpu
  epochs: 100
  iter_save: 5
  batch_size: 100
  log_interval: 10
  lr: 0.0008
  accumulation_steps: 1
  dropout: 0.2
  criterion:
    "0": MSELoss
    "1": MSELoss
    "2": MSELoss
    "3": MSELoss
    "4": MSELoss
    "5": MSELoss
    "6": MSELoss
    "7": MSELoss
    "8": MSELoss
    "9": MSELoss
    "10": MSELoss
    "11": MSELoss
    "12": MSELoss
    "13": MSELoss
    "14": MSELoss
    "15": MSELoss
    "16": MSELoss
    "17": MSELoss
    "18": MSELoss
    "19": MSELoss
    "20": MSELoss
    "21": MSELoss
    "22": MSELoss
    "23": MSELoss
    "24": MSELoss
    "25": MSELoss
    "26": MSELoss
    "27": MSELoss
    "28": MSELoss
    "29": MSELoss
    "30": MSELoss
    "31": MSELoss
    "32": MSELoss
    "33": MSELoss
    "34": MSELoss
    "35": MSELoss
    "36": MSELoss
    "37": MSELoss
    "38": MSELoss
    "39": MSELoss
    "40": MSELoss
    "41": MSELoss
    "42": MSELoss
    "43": MSELoss
    "44": MSELoss
    "45": MSELoss
    "46": MSELoss
    "47": MSELoss
    "48": MSELoss
    "49": MSELoss
    "50": MSELoss
    "51": MSELoss
    "52": MSELoss
    "53": MSELoss
    "54": MSELoss
    "55": MSELoss
    "56": MSELoss
    "57": MSELoss
    "58": MSELoss
    "59": MSELoss
    "60": MSELoss
    "61": MSELoss
    "62": MSELoss
    "63": MSELoss
    "64": MSELoss
    "65": MSELoss
    "66": MSELoss
    "67": MSELoss
    "68": MSELoss
    "69": MSELoss
    "70": MSELoss
    "71": MSELoss
    "72": MSELoss
    "73": MSELoss
    "74": MSELoss
    "75": MSELoss
    "76": MSELoss
    "77": MSELoss
    "78": MSELoss
    "79": MSELoss
    "80": MSELoss
    "81": MSELoss
    "82": MSELoss
    "83": MSELoss
    "84": MSELoss
    "85": MSELoss
    "86": MSELoss
    "87": MSELoss
    "88": MSELoss
    "89": MSELoss
    "90": MSELoss
    "91": MSELoss
    "92": MSELoss
    "93": MSELoss
    "94": MSELoss
    "95": MSELoss
    "96": MSELoss
    "97": MSELoss
    "98": MSELoss
    "99": MSELoss
    "100": MSELoss
    "101": MSELoss
    "102": MSELoss
    "103": MSELoss
    "104": MSELoss
    "105": MSELoss
    "106": MSELoss
    "107": MSELoss
    "108": MSELoss
    "109": MSELoss
    "110": MSELoss
    "111": MSELoss
    "112": MSELoss
    "113": MSELoss
    "114": MSELoss
    "115": MSELoss
    "116": MSELoss
    "117": MSELoss
    "118": MSELoss
    "119": MSELoss
    "120": MSELoss
    "121": MSELoss
    "122": MSELoss
    "123": MSELoss
    "124": MSELoss
    "125": MSELoss
    "126": MSELoss
    "127": MSELoss
    "128": MSELoss
    "129": MSELoss
    "130": MSELoss
    "131": MSELoss
    "132": MSELoss
    "133": MSELoss
    "134": MSELoss
    "135": MSELoss
    "136": MSELoss
  optimizer:
    name: AdamW
  scheduler:
    name: StepLR
    step_size: 1
    gamma: 0.95
  continue_training: false